'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class LessonList
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CAI.LessonList", GetType(LessonList).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Public Shared ReadOnly Property lesson_list_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lesson_list.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Public Shared ReadOnly Property lesson_next_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lesson_next.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Public Shared ReadOnly Property lesson_page_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lesson_page.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Public Shared ReadOnly Property lesson_prev_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lesson_prev.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Rectangle similar to {X=685,Y=71,Width=358,Height=0}.
        '''</summary>
        Public Shared ReadOnly Property LineShape1_Bounds() As System.Drawing.Rectangle
            Get
                Dim obj As Object = ResourceManager.GetObject("LineShape1.Bounds", resourceCulture)
                Return CType(obj,System.Drawing.Rectangle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=685,Y=71}.
        '''</summary>
        Public Shared ReadOnly Property LineShape1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LineShape1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=358, Height=0}.
        '''</summary>
        Public Shared ReadOnly Property LineShape1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("LineShape1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Rectangle similar to {X=624,Y=59,Width=374,Height=0}.
        '''</summary>
        Public Shared ReadOnly Property LineShape2_Bounds() As System.Drawing.Rectangle
            Get
                Dim obj As Object = ResourceManager.GetObject("LineShape2.Bounds", resourceCulture)
                Return CType(obj,System.Drawing.Rectangle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=624,Y=59}.
        '''</summary>
        Public Shared ReadOnly Property LineShape2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("LineShape2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=374, Height=0}.
        '''</summary>
        Public Shared ReadOnly Property LineShape2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("LineShape2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Public Shared ReadOnly Property Panel2_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Panel2.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
    End Class
End Namespace
